apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: towfiqueahmmed/voting_app_project2:v3
          ports:
            - containerPort: 80
          env:
            - name: OPTION_A
              value: "Cats"
            - name: OPTION_B
              value: "Dogs"
            - name: REDIS_HOST
              value: "redis" 
---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: voting-app
spec:
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP 
